"""create_phone_table

Revision ID: 00b513883396
Revises: 
Create Date: 2020-12-19 11:03:51.285520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00b513883396'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phone',
    sa.Column('phone_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('available', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('phone_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('phone')
    # ### end Alembic commands ###
